sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234
  # 已禁用该 key，如需使用重新获取
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5t9RLSbHseyzVjZHgx5q
    access-key-secret: Nod7qMlR13tXQyYoiRB8DFspDsX5ei
    bucket-name: gajzj-tlias